import { ArrowRight, MapPin, Search as SearchIcon, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { geocodeAddress } from '../lib/api'

export function Search({ onSubmit }: { onSubmit: (place: { lat: number; lon: number; label: string }) => void }) {
  const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!query.trim()) return; setLoading(true); setError(''); try { const result = await geocodeAddress(query.trim()); if (!result) throw new Error('No location found. Try a more specific address or locality.'); onSubmit({ lat: result.lat, lon: result.lon, label: result.display_name }) } catch (e) { setError(e instanceof Error ? e.message : 'Search failed') } finally { setLoading(false) } }
  return <main className="search-screen"><div className="search-grid" /><header className="wordmark"><span className="mark"><Sparkles size={15} /></span> TERRASCOPE <span className="wordmark-rule" /> REVIEW 02</header><section className="search-hero"><div className="eyebrow"><span className="pulse" /> LAND DUE DILIGENCE, WITH CONTEXT</div><h1>See the land<br /><em>before you commit.</em></h1><p className="hero-copy">A clear, evidence-led read on the parcel beneath the promise. Start with a place.</p><form className="search-form" onSubmit={submit}><SearchIcon size={19} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search an address, locality or coordinates" aria-label="Search an address, locality or coordinates" /><button className="icon-button submit-button" disabled={loading} aria-label="Search"><ArrowRight size={19} /></button></form>{error && <p className="form-error">{error}</p>}<div className="search-note"><MapPin size={14} /> Pune, Maharashtra is ready for your first review</div></section><footer className="search-footer"><span>Satellite signals</span><span>Land records</span><span>Infrastructure</span><span>One decision surface</span></footer></main>
}
