export type GeoJSONPolygon = { type: 'Polygon'; coordinates: number[][][] }
export type Freshness = 'live' | 'cached' | 'seed_data' | 'user_upload' | 'derived'
export type Recommendation = 'BUY' | 'WAIT' | 'AVOID' | 'INSUFFICIENT_EVIDENCE'
export interface Location { latitude: number|null; longitude: number|null; address: string|null; village: string|null; district: string|null; state: string|null; pincode: string|null }
export interface GeometryMetadata { area_m2: number|null; area_acres: number|null; perimeter_m: number|null; boundary_source: 'user_drawn'|'imported'|'estimated'|'unknown'|null; boundary_verified: boolean|null }
export interface LandRecords { survey_number: string|null; ownership_type: 'freehold'|'leasehold'|'disputed'|'unknown'|null; title_clear: boolean|null; encumbrance_flag: boolean|null; source_document_ids: (string|null)[]|null }
export interface SatellitePoint { date: string|null; value: number|null }
export interface Satellite { imagery_dates: (string|null)[]|null; ndvi_trend: SatellitePoint[]|null; ndbi_trend: SatellitePoint[]|null; change_detected: boolean|null; change_type: 'construction_growth'|'vegetation_loss'|'no_change'|'insufficient_evidence'|null; change_confidence: number|null }
export interface EvidenceItem { evidence_id?: string|null; source_type?: string|null; source_reference?: string|null; title?: string|null; observed_at?: string|null; freshness?: Freshness|null; summary?: string|null; licence?: string|null; resolution?: string|null; observation_period?: string|null }
export type FactorStatus = 'assessed' | 'indicative' | 'unavailable' | 'not_integrated'
export interface FactorAssessment { factor: string; score: number|null; status: FactorStatus; basis: string; limitations: string; weight_pct: number; checklist: string[]|null }
export interface ScoreBreakdown { legal_safety_score: number|null; accessibility_score: number|null; flood_safety_score: number|null; growth_score: number|null; composite_score?: number|null; weighted_contributions: { factor: string|null; contribution: number|null }[]|null; factors?: FactorAssessment[]|null; assessed_weight_pct?: number|null; unassessed_factors?: string[]|null }
export interface Verdict { recommendation: Recommendation; confidence: number|null; reasoning_summary: string; citations: { claim: string; source_type: string; source_reference: string }[] }
export interface EvaluationSettings { profile: 'homebuyer'|'developer'|'investor'|'conservative'|'custom'; property_type: 'residential'|'commercial'|'industrial'|'mixed_use'; investment_horizon: 'under_1y'|'1_to_3y'|'3_to_5y'|'5_to_10y'|'10_plus_y'; weights: { growth_pct: number; legal_safety_pct: number; accessibility_pct: number; flood_safety_pct: number }; preferences: { road_importance: 'low'|'medium'|'high'; school_importance: 'low'|'medium'|'high'; max_road_distance_m: number; max_school_distance_m: number; rera_requirement: 'strict'|'important'|'informational' } }
export interface ParcelRecord { parcel_id: string|null; location: Location|null; geometry: GeoJSONPolygon|null; geometry_metadata: GeometryMetadata|null; land_records: LandRecords|null; rera: { is_rera_project: boolean|null; rera_registration_number: string|null; promoter_name: string|null; registered_completion_date: string|null; source_url: string|null }|null; satellite: Satellite|null; infrastructure: { nearest_road_distance_m: number|null; nearest_road_type: string|null; nearest_school_distance_m: number|null; nearest_road_lat?: number|null; nearest_road_lon?: number|null; nearest_school_lat?: number|null; nearest_school_lon?: number|null }|null; risk: { flood_risk_score: number|null; flood_risk_basis: string|null; elevation_m: number|null; legal_risk_score: number|null; accessibility_score: number|null; terrain_relative_elevation_score?: number|null; terrain_basis?: string|null; flood_assessment_status?: string|null }|null; opportunity: { growth_score: number|null; infra_growth_trend: 'rising'|'stable'|'declining'|null }|null; evaluation?: EvaluationSettings|null; score_breakdown?: ScoreBreakdown|null; evidence: EvidenceItem[]|null; verdict: Verdict|null; metadata: { last_updated: string|null; data_completeness_pct: number|null; analysis_date_from: string|null; analysis_date_to: string|null; analysis_snapshot_id: string|null } }
export interface AnalysisResponse { analysis_snapshot_id: string; evidence_snapshot: ParcelRecord }
export interface CoverageResult { status: 'inside'|'outside'; reason: string|null; boundary_source: string|null; boundary_licence: string|null; boundary_as_of: string|null }
export type AnalysisResult = AnalysisResponse | { status: 'outside_coverage'; coverage: CoverageResult }
const API_URL = (import.meta.env.VITE_BACKEND_API_URL || 'http://localhost:8000').replace(/\/$/, '')
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_URL}${path}`, { headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) }, ...init }); if (!response.ok) throw new Error((await response.text()) || `Request failed (${response.status})`); return response.json() as Promise<T> }
export type PlaceSuggestion = { lat: number; lon: number; display_name: string }
export async function geocodeSuggestions(address: string): Promise<PlaceSuggestion[]> { const key = `terrascope:geocode:${address.trim().toLowerCase()}`; const cached = sessionStorage.getItem(key); if (cached) { const parsed = JSON.parse(cached) as PlaceSuggestion[] | PlaceSuggestion | null; return Array.isArray(parsed) ? parsed : parsed ? [parsed] : [] } const payload = await request<PlaceSuggestion[] | PlaceSuggestion | null>(`/api/v1/search/geocode?q=${encodeURIComponent(address.trim())}`); const result = Array.isArray(payload) ? payload : payload ? [payload] : []; sessionStorage.setItem(key, JSON.stringify(result)); return result }
export async function geocodeAddress(address: string): Promise<PlaceSuggestion|null> { const results = await geocodeSuggestions(address); return results[0] || null }
export function buildAnalysis(payload: { polygon: GeoJSONPolygon; address?: string; analysis_date_from: string; analysis_date_to: string }) { return request<AnalysisResult>('/api/v1/parcels/analyze', { method: 'POST', body: JSON.stringify(payload) }) }
export function evaluateParcel(parcelId: string, settings: EvaluationSettings, snapshotId: string) { return request<ParcelRecord>(`/api/v1/parcels/${encodeURIComponent(parcelId)}/evaluate`, { method: 'POST', body: JSON.stringify({ analysis_snapshot_id: snapshotId, ...settings }) }) }
export async function uploadEvidence(parcelId: string, file: File) { const form = new FormData(); form.append('file', file); const response = await fetch(`${API_URL}/api/v1/parcels/${encodeURIComponent(parcelId)}/documents`, { method: 'POST', body: form }); if (!response.ok) throw new Error((await response.text()) || 'Upload failed'); return response.json() as Promise<{ document_id: number; filename: string; text_indexed: boolean }> }

export type LandUse = 'residential' | 'commercial' | 'industrial' | 'agricultural' | 'mixed_use'
export type PriceBasis = 'transaction' | 'asking'
/** Property facts the user supplies; they drive valuation, never the suitability weights. */
export interface PropertyDetails { land_use: LandUse; price_basis: PriceBasis; area_sqft_override: number | null }
export interface ValuationAccuracy { holdout_strategy: string; holdout_description: string; model_mae_inr_per_sqft: number; model_rmse_inr_per_sqft: number; baseline_mae_inr_per_sqft: number; baseline_rmse_inr_per_sqft: number; model_beats_baseline: boolean }
export interface ValuationCoverage { nearest_observation_km: number | null; observations_within_radius: number; radius_km: number; districts_nearby: string[]; dataset_rows: number; dataset_date_from: string; dataset_date_to: string; price_basis_counts: Record<string, number> }
export interface ValuationRange { low_inr_per_sqft: number; high_inr_per_sqft: number; low_total_inr: number; high_total_inr: number; nominal_coverage_pct: number; measured_holdout_coverage_pct: number; basis: string }
export interface ValuationAvailable { status: 'available'; estimated_inr_per_sqft: number; estimated_total_inr: number; area_sqft: number; range: ValuationRange | null; range_unavailable_reason: string | null; land_use: string; valuation_date: string; model_version: string; data_version: string; trained_at: string; is_synthetic: boolean; accuracy: ValuationAccuracy; evidence_coverage: ValuationCoverage }
export interface ValuationUnavailable { status: 'unavailable'; reason: string; detail: string }
export type Valuation = ValuationAvailable | ValuationUnavailable
export interface SavedReport { parcel_id: string; analysis_snapshot_id: string; created_at: string; address: string | null; district: string | null; area_acres: number | null; analysis_date_from: string | null; analysis_date_to: string | null; document_count: number; has_evaluation: boolean }

export function estimateValuation(payload: { latitude: number; longitude: number; area_sqft: number; land_use: string; price_basis: string }) {
  return request<Valuation>('/api/v1/valuation/estimate', { method: 'POST', body: JSON.stringify(payload) })
}
export function listSavedReports() { return request<{ reports: SavedReport[] }>('/api/v1/parcels').then(payload => payload.reports) }
export function getSavedParcel(parcelId: string) {
  return request<{ parcel_id: string; analysis_snapshot_id: string; evidence_snapshot: ParcelRecord; uploaded_documents: { source_reference: string }[]; latest_evaluation: ParcelRecord | null }>(`/api/v1/parcels/${encodeURIComponent(parcelId)}`)
}
