export type GeoJSONPolygon = { type: 'Polygon'; coordinates: number[][][] }
export type Freshness = 'live' | 'cached' | 'seed_data' | 'user_upload' | 'derived'
export type Recommendation = 'BUY' | 'WAIT' | 'AVOID'
export interface Location { latitude: number|null; longitude: number|null; address: string|null; village: string|null; district: string|null; state: string|null; pincode: string|null }
export interface GeometryMetadata { area_m2: number|null; area_acres: number|null; perimeter_m: number|null; boundary_source: 'user_drawn'|'imported'|'estimated'|'unknown'|null; boundary_verified: boolean|null }
export interface LandRecords { survey_number: string|null; ownership_type: 'freehold'|'leasehold'|'disputed'|'unknown'|null; title_clear: boolean|null; encumbrance_flag: boolean|null; source_document_ids: (string|null)[]|null }
export interface SatellitePoint { date: string|null; value: number|null }
export interface Satellite { imagery_dates: (string|null)[]|null; ndvi_trend: SatellitePoint[]|null; ndbi_trend: SatellitePoint[]|null; change_detected: boolean|null; change_type: 'construction_growth'|'vegetation_loss'|'no_change'|'insufficient_evidence'|null; change_confidence: number|null }
export interface EvidenceItem { evidence_id?: string|null; source_type?: string|null; source_reference?: string|null; title?: string|null; observed_at?: string|null; freshness?: Freshness|null; summary?: string|null }
export interface ScoreBreakdown { legal_safety_score: number|null; accessibility_score: number|null; flood_safety_score: number|null; growth_score: number|null; composite_score?: number|null; weighted_contributions: { factor: string|null; contribution: number|null }[]|null }
export interface Verdict { recommendation: Recommendation; confidence: number; reasoning_summary: string; citations: { claim: string; source_type: string; source_reference: string }[] }
export interface EvaluationSettings { profile: 'homebuyer'|'developer'|'investor'|'conservative'|'custom'; property_type: 'residential'|'commercial'|'industrial'|'mixed_use'; investment_horizon: 'under_1y'|'1_to_3y'|'3_to_5y'|'5_to_10y'|'10_plus_y'; weights: { growth_pct: number; legal_safety_pct: number; accessibility_pct: number; flood_safety_pct: number }; preferences: { road_importance: 'low'|'medium'|'high'; school_importance: 'low'|'medium'|'high'; max_road_distance_m: number; max_school_distance_m: number; rera_requirement: 'strict'|'important'|'informational' } }
export interface ParcelRecord { parcel_id: string|null; location: Location|null; geometry: GeoJSONPolygon|null; geometry_metadata: GeometryMetadata|null; land_records: LandRecords|null; rera: { is_rera_project: boolean|null; rera_registration_number: string|null; promoter_name: string|null; registered_completion_date: string|null; source_url: string|null }|null; satellite: Satellite|null; infrastructure: { nearest_road_distance_m: number|null; nearest_road_type: string|null; nearest_school_distance_m: number|null }|null; risk: { flood_risk_score: number|null; flood_risk_basis: string|null; elevation_m: number|null; legal_risk_score: number|null; accessibility_score: number|null }|null; opportunity: { growth_score: number|null; infra_growth_trend: 'rising'|'stable'|'declining'|null }|null; evaluation?: EvaluationSettings|null; score_breakdown?: ScoreBreakdown|null; evidence: EvidenceItem[]|null; verdict: Verdict|null; metadata: { last_updated: string|null; data_completeness_pct: number|null; analysis_date_from: string|null; analysis_date_to: string|null; analysis_snapshot_id: string|null } }
export interface AnalysisResponse { analysis_snapshot_id: string; evidence_snapshot: ParcelRecord }
const API_URL = (import.meta.env.VITE_BACKEND_API_URL || 'http://localhost:8000').replace(/\/$/, '')
async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API_URL}${path}`, { headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) }, ...init }); if (!response.ok) throw new Error((await response.text()) || `Request failed (${response.status})`); return response.json() as Promise<T> }
export async function geocodeAddress(address: string): Promise<{ lat: number; lon: number; display_name: string }|null> { const key = `terrascope:geocode:${address.trim().toLowerCase()}`; const cached = sessionStorage.getItem(key); if (cached) return JSON.parse(cached) as { lat: number; lon: number; display_name: string }; const result = await request<{ lat: number; lon: number; display_name: string }|null>(`/api/v1/search/geocode?q=${encodeURIComponent(address.trim())}`); if (result) sessionStorage.setItem(key, JSON.stringify(result)); return result }
export function buildAnalysis(payload: { polygon: GeoJSONPolygon; address?: string; analysis_date_from: string; analysis_date_to: string }) { return request<AnalysisResponse>('/api/v1/parcels/analyze', { method: 'POST', body: JSON.stringify(payload) }) }
export function evaluateParcel(parcelId: string, settings: EvaluationSettings, snapshotId: string) { return request<ParcelRecord>(`/api/v1/parcels/${encodeURIComponent(parcelId)}/evaluate`, { method: 'POST', body: JSON.stringify({ analysis_snapshot_id: snapshotId, ...settings }) }) }
export async function uploadEvidence(parcelId: string, file: File) { const form = new FormData(); form.append('file', file); const response = await fetch(`${API_URL}/api/v1/parcels/${encodeURIComponent(parcelId)}/documents`, { method: 'POST', body: form }); if (!response.ok) throw new Error((await response.text()) || 'Upload failed'); return response.json() as Promise<{ document_id: number; filename: string; text_indexed: boolean }> }
